### ISSUE TITLE
Configuration setting to allow all users to save powerviews

### ISSUE THREAD

**Issue by danmihaila** [OCHA-DAP/ckanext-powerview#1]
Implement a configuration setting that could allow users to save powerviews. The default behaviour is that only sysadmins can save a powerview

**Comment by brew** [comment]
- [ ] Auth for powerview_add_resource
- [ ] Auth for powerview_remove_resource

**Comment by brew** [comment]
See commit 15e17f6818183a34e69ce28537f1dd2c36981e14 for create, update and delete actions.

**Comment by brew** [comment]
See commit bb8eff53b76dea4f4be3c03ff49de47f01152174 for add_resource and remove_resource action auth.

**Comment by brew** [comment]
@danmihaila This is now done!
